### ISSUE TITLE
Investigate: Refresh token expires

### ISSUE THREAD

**Issue by reneaaron** [getAlby/oauth2server#59]
Kim from cowlabs reported that refresh tokens seem to expire at the same time the access_token is expiring. (he is still investigating on his side)

While the `SetAuthorizeCodeCfg` seems to use the token expiration from the config, the `RefreshTokenCfg` seems not: :thinking: 

https://github.com/getAlby/oauth2server/blob/chore/upgrade-orm-packages/service/service.go#L66-L81

Shouldn't the RefreshTokenExpiration be set there as well? 

Would be great to get your opinion if there could be an issue on our side @kiwiidb.

**Comment by kiwiidb** [comment]
This issue was found to be on cowlabs side: https://getalby.slack.com/archives/C04RN9W9MB9/p1685534299659989?thread_ts=1684933861.318639&cid=C04RN9W9MB9
